# -*- coding: utf-8 -*-
"""webscraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IEtoJoeZAFhdnVNrn5JAeygOvh131c-M

This program scrapes then news from news article & summarise them

Importing Libraries
"""

import nltk
from newspaper import Article

"""Get the Article"""

url = 'https://www.reuters.com/article/ethiopia-conflict/ethiopia-war-may-turn-into-guerrilla-insurgency-idUSKBN28B58K'
article = Article(url)

"""Natural Language Processing on the data"""

article.download()
article.parse()
nltk.download('punkt')
article.nlp()

"""Identifying Authors"""

article.authors

"""Get Published Date"""

article.publish_date

"""Get Article feature Image"""

article.top_image

"""Text from the article"""

r = article.text
print(r)

"""Summarising article"""

summary = article.summary
print(summary)